// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interfaces/questionRepoInterface.go

// Package mock is a generated GoMock package.
package mock

import (
	models "localEyes/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockQuestionRepository is a mock of QuestionRepository interface.
type MockQuestionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockQuestionRepositoryMockRecorder
}

// MockQuestionRepositoryMockRecorder is the mock recorder for MockQuestionRepository.
type MockQuestionRepositoryMockRecorder struct {
	mock *MockQuestionRepository
}

// NewMockQuestionRepository creates a new mock instance.
func NewMockQuestionRepository(ctrl *gomock.Controller) *MockQuestionRepository {
	mock := &MockQuestionRepository{ctrl: ctrl}
	mock.recorder = &MockQuestionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuestionRepository) EXPECT() *MockQuestionRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockQuestionRepository) Create(question *models.Question) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", question)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockQuestionRepositoryMockRecorder) Create(question interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockQuestionRepository)(nil).Create), question)
}

// DeleteByPId mocks base method.
func (m *MockQuestionRepository) DeleteByPId(pId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByPId", pId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByPId indicates an expected call of DeleteByPId.
func (mr *MockQuestionRepositoryMockRecorder) DeleteByPId(pId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByPId", reflect.TypeOf((*MockQuestionRepository)(nil).DeleteByPId), pId)
}

// DeleteByQId mocks base method.
func (m *MockQuestionRepository) DeleteByQId(qId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByQId", qId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByQId indicates an expected call of DeleteByQId.
func (mr *MockQuestionRepositoryMockRecorder) DeleteByQId(qId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByQId", reflect.TypeOf((*MockQuestionRepository)(nil).DeleteByQId), qId)
}

// DeleteByQIdUId mocks base method.
func (m *MockQuestionRepository) DeleteByQIdUId(qId, uId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByQIdUId", qId, uId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByQIdUId indicates an expected call of DeleteByQIdUId.
func (mr *MockQuestionRepositoryMockRecorder) DeleteByQIdUId(qId, uId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByQIdUId", reflect.TypeOf((*MockQuestionRepository)(nil).DeleteByQIdUId), qId, uId)
}

// GetAllQuestions mocks base method.
func (m *MockQuestionRepository) GetAllQuestions() ([]*models.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllQuestions")
	ret0, _ := ret[0].([]*models.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllQuestions indicates an expected call of GetAllQuestions.
func (mr *MockQuestionRepositoryMockRecorder) GetAllQuestions() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllQuestions", reflect.TypeOf((*MockQuestionRepository)(nil).GetAllQuestions))
}

// GetQuestionsByPId mocks base method.
func (m *MockQuestionRepository) GetQuestionsByPId(pId string) ([]*models.Question, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetQuestionsByPId", pId)
	ret0, _ := ret[0].([]*models.Question)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetQuestionsByPId indicates an expected call of GetQuestionsByPId.
func (mr *MockQuestionRepositoryMockRecorder) GetQuestionsByPId(pId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetQuestionsByPId", reflect.TypeOf((*MockQuestionRepository)(nil).GetQuestionsByPId), pId)
}

// UpdateQuestion mocks base method.
func (m *MockQuestionRepository) UpdateQuestion(qId, answer string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateQuestion", qId, answer)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateQuestion indicates an expected call of UpdateQuestion.
func (mr *MockQuestionRepositoryMockRecorder) UpdateQuestion(qId, answer interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateQuestion", reflect.TypeOf((*MockQuestionRepository)(nil).UpdateQuestion), qId, answer)
}
