// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interfaces/postRepoInterface.go

// Package mock is a generated GoMock package.
package mock

import (
	models "localEyes/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockPostRepository is a mock of PostRepository interface.
type MockPostRepository struct {
	ctrl     *gomock.Controller
	recorder *MockPostRepositoryMockRecorder
}

// MockPostRepositoryMockRecorder is the mock recorder for MockPostRepository.
type MockPostRepositoryMockRecorder struct {
	mock *MockPostRepository
}

// NewMockPostRepository creates a new mock instance.
func NewMockPostRepository(ctrl *gomock.Controller) *MockPostRepository {
	mock := &MockPostRepository{ctrl: ctrl}
	mock.recorder = &MockPostRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostRepository) EXPECT() *MockPostRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockPostRepository) Create(post *models.Post) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", post)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockPostRepositoryMockRecorder) Create(post interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPostRepository)(nil).Create), post)
}

// DeleteByPId mocks base method.
func (m *MockPostRepository) DeleteByPId(pId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByPId", pId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByPId indicates an expected call of DeleteByPId.
func (mr *MockPostRepositoryMockRecorder) DeleteByPId(pId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByPId", reflect.TypeOf((*MockPostRepository)(nil).DeleteByPId), pId)
}

// DeleteByUIdPId mocks base method.
func (m *MockPostRepository) DeleteByUIdPId(uId, pId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUIdPId", uId, pId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUIdPId indicates an expected call of DeleteByUIdPId.
func (mr *MockPostRepositoryMockRecorder) DeleteByUIdPId(uId, pId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUIdPId", reflect.TypeOf((*MockPostRepository)(nil).DeleteByUIdPId), uId, pId)
}

// GetAllPosts mocks base method.
func (m *MockPostRepository) GetAllPosts() ([]*models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllPosts")
	ret0, _ := ret[0].([]*models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllPosts indicates an expected call of GetAllPosts.
func (mr *MockPostRepositoryMockRecorder) GetAllPosts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllPosts", reflect.TypeOf((*MockPostRepository)(nil).GetAllPosts))
}

// GetPostByPId mocks base method.
func (m *MockPostRepository) GetPostByPId(pId string) (*models.PostWithQuestions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostByPId", pId)
	ret0, _ := ret[0].(*models.PostWithQuestions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostByPId indicates an expected call of GetPostByPId.
func (mr *MockPostRepositoryMockRecorder) GetPostByPId(pId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostByPId", reflect.TypeOf((*MockPostRepository)(nil).GetPostByPId), pId)
}

// GetPostsByFilter mocks base method.
func (m *MockPostRepository) GetPostsByFilter(filter string) ([]*models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostsByFilter", filter)
	ret0, _ := ret[0].([]*models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostsByFilter indicates an expected call of GetPostsByFilter.
func (mr *MockPostRepositoryMockRecorder) GetPostsByFilter(filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostsByFilter", reflect.TypeOf((*MockPostRepository)(nil).GetPostsByFilter), filter)
}

// GetPostsByUId mocks base method.
func (m *MockPostRepository) GetPostsByUId(uId string) ([]*models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPostsByUId", uId)
	ret0, _ := ret[0].([]*models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPostsByUId indicates an expected call of GetPostsByUId.
func (mr *MockPostRepositoryMockRecorder) GetPostsByUId(uId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPostsByUId", reflect.TypeOf((*MockPostRepository)(nil).GetPostsByUId), uId)
}

// UpdateLike mocks base method.
func (m *MockPostRepository) UpdateLike(pId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateLike", pId)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateLike indicates an expected call of UpdateLike.
func (mr *MockPostRepositoryMockRecorder) UpdateLike(pId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateLike", reflect.TypeOf((*MockPostRepository)(nil).UpdateLike), pId)
}

// UpdateUserPost mocks base method.
func (m *MockPostRepository) UpdateUserPost(pId, uId, title, content string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateUserPost", pId, uId, title, content)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateUserPost indicates an expected call of UpdateUserPost.
func (mr *MockPostRepositoryMockRecorder) UpdateUserPost(pId, uId, title, content interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateUserPost", reflect.TypeOf((*MockPostRepository)(nil).UpdateUserPost), pId, uId, title, content)
}
